# Part of Odoo. See LICENSE file for full copyright and licensing details.

from . import common
from . import test_payment_method_amount_limits
from . import test_buckaroo_surcharge
from . import test_payment_method_data
from . import test_payment_provider
from . import test_processing_flows
from . import test_push_handlers
from . import test_helpers
from . import test_hosted_fields
from . import test_payment_method_sdk
from . import test_payment_method_bank_transfer
from . import test_payment_method_billink
from . import test_payment_method_in3
from . import test_payment_method_klarna
from . import test_payment_method_riverty
from . import test_payment_method_creditcard
from . import test_payment_method_giftcard
from . import test_capture_push
from . import test_giftcard_summary
from . import test_payment_method_googlepay
from . import test_payment_method_applepay
from . import test_payment_method_paypal
from . import test_payment_method_paypal_express
from . import test_payment_method_paypermail
from . import test_payment_method_sdk_contract
from . import test_transaction_model_dispatch
from . import test_account_move_refund
